### ISSUE TITLE
can you show a picture shown how camera was set with UR ,

### ISSUE THREAD

**Issue by dbdxnuliba** [atenpas/gpd#101]
can you show a picture shown how camera was set with UR ,
in the video in youtube I can't see clearly where is the camera

**Comment by atenpas** [comment]
The camera is mounted on the robot's wrist. It looks along the fingers. It's mounted similar to this:
![image](https://user-images.githubusercontent.com/5692966/89938339-5dbe4b00-dbe4-11ea-8436-d55f6a42c919.png)

**Comment by dbdxnuliba** [comment]
thanks  a lot
is it realsense ?
and will the usb line of camera  be too short for us to connect PC?
and do you use only single rgbd camera in the scence

**Comment by atenpas** [comment]
No, the sensor is a Structure made by Occipital. I don't know if they still make it.

You can buy a long cable and/or an extension cable.

Yes, it's a single sensor, but it looks at the scene from two different viewpoints.

**Comment by dbdxnuliba** [comment]
I see ,thanks a lot
