### ISSUE TITLE
About the low quality of grasping pose

### ISSUE THREAD

**Issue by lsattf** [atenpas/gpd#119]
The algorithm cannot detect the objects in the scene very well. But the paper mentioned it has the object detection or segmantation algorithm included. Do I need to do the object detection in point cloud myself before feed into the package or I used the package incorrectly?

Here is the test result from a .pcd file with some objects on the table, you  can see it just detect one or two of the obejcts and generate some pose on wall and table legs:
![Screenshot from 2021-10-14 15-36-51](https://user-images.githubusercontent.com/58330520/137340760-6c856da9-9736-4833-90d4-f33c15b952d0.png)

**Comment by atenpas** [comment]
Yes, you need to do the object detection method. GPD's purpose is to detect grasp poses, not objects.
