### ISSUE TITLE
Documentation about Parameters

### ISSUE THREAD

**Issue by jeoseo** [atenpas/gpd#121]
Does anyone have more in depth documentation about the parameters of the robot hand and grasp descriptors? I'm confused as to how to describe the gripper such that it only tries to grasp with the tip of the gripper, and not try to grab using the linkage inwards of the fingers.

The gripper in question is this: https://www.ufactory.cc/products/xarm-gripper-2020
    
    # ==== Robot Hand Geometry ====
    #   finger_width: the width of the finger
    #   outer_diameter: the diameter of the robot hand (= maximum aperture + 2 * finger width)
    #   hand_depth: the finger length (measured from hand base to finger tip)
    #   hand_height: the height of the hand
    #   init_bite: the minimum amount of the object to be covered by the hand
    finger_width = 0.02
    hand_outer_diameter = 0.12
    hand_depth = .06
    hand_height = 0.02
    init_bite = 0.01
    
    # ==== Grasp Descriptor ==== (cm)
    #   volume_width: the width of the cube inside the robot hand
    #   volume_depth: the depth of the cube inside the robot hand
    #   volume_height: the height of the cube inside the robot hand
    #   image_size: the size of the image (width and height; image is square)
    #   image_num_channels: the number of image channels
    volume_width = 0.08
    volume_depth = 0.06
    volume_height = 0.02
    image_size = 60
    image_num_channels = 15

**Comment by atenpas** [comment]
GPD always pushes the hand's base forward as much as possible (until it contacts an object). You can turn this off by setting `deepen_hand = 0` in the CFG file.
