### ISSUE TITLE
How can we fetch Grasp pose values from code after successful grasp detection ??

### ISSUE THREAD

**Issue by aniketghodake10** [atenpas/gpd#124]
It doesnt print the grasp pose vaules. It just visualizes the grasp. Any way can we fetch those grasp pose values ??

**Comment by ximiluuuu** [comment]
> It doesnt print the grasp pose vaules. It just visualizes the grasp. Any way can we fetch those grasp pose values ??它不会打印抓取姿势 vaules。它只是将抓握形象化。我们有什么方法可以获取那些抓取姿势值吗？
HI,
I'm stuck in the same situation, were you able to solve it?
