### ISSUE TITLE
Can you ask if there is a full paper to refer to?

### ISSUE THREAD

**Issue by wwh01875** [atenpas/gpd#129]
hello dear author
I have checked the journal you submitted your manuscript to. I am very interested in the algorithm in it. Can you trouble the author to provide me with the complete paper by email or other means for me to refer to? I need it very much.
Thank you

**Comment by atenpas** [comment]
Here you go: [conference paper](http://www.ccs.neu.edu/home/atp/publications/grasps_cnn_iros2016.pdf) and [journal paper](https://arxiv.org/abs/1706.09911).
