### ISSUE TITLE
Segmentation fault (on Ubuntu 22.04)

### ISSUE THREAD

**Issue by Ca11m3X** [atenpas/gpd#142]
Hi, I'm trying to install GPD on Ubuntu 22.04 but I have a **"Segmentation Fault"** issue when running the example `./detect_grasps ../cfg/eigen_params.cfg ../tutorials/krylon.pcd`. 

![Screenshot from 2024-09-30 11-47-02](https://github.com/user-attachments/assets/8c942bc1-741c-4ee4-9acc-ee26888cc709)

I just install by default. There are some information about my hardware:

![Screenshot from 2024-09-30 11-49-26](https://github.com/user-attachments/assets/aa46ab31-f25f-4a90-8d70-9739409d04c1)

Thanks for your support.

**Comment by atenpas** [comment]
Can you comment out [this line](https://github.com/atenpas/gpd/blob/master/CMakeLists.txt#L29) and try again?

**Comment by Ca11m3X** [comment]
> Can you comment out [this line](https://github.com/atenpas/gpd/blob/master/CMakeLists.txt#L29) and try again?

Thanks for your reply, but when I comment whole the line, it caused some errors: `‘omp_get_wtime’ was not declared in this scope` and `recompile with -fPIC`. Then I fix this by `set(CMAKE_CXX_FLAGS "-fopenmp -fPIC")` only, it built successfully but it still `Segmentation fault`.

**Comment by atenpas** [comment]
Could you try https://github.com/atenpas/gpd/issues/103#issuecomment-734152660?

**Comment by Ca11m3X** [comment]
> Could you try [#103 (comment)](https://github.com/atenpas/gpd/issues/103#issuecomment-734152660)?

I had tried this solution before but not work.

**Comment by atenpas** [comment]
Could you run it in gdb and post the backtrace?

**Comment by Ca11m3X** [comment]
> Could you run it in gdb and post the backtrace?

Sorry for slow response, I had ran the `./detect_grasps ../cfg/eigen_params.cfg ../tutorials/krylon.pcd` in gpd with build setup `set(CMAKE_CXX_FLAGS "-fopenmp -fPIC -Wno-deprecated -Wenum-compare -Wno-ignored-attributes -std=c++14")` then the error caused by the line as below:
![Screenshot from 2024-10-03 16-14-35](https://github.com/user-attachments/assets/02ebb154-5dd9-4655-bd9a-42022b4ccab5)
If its not enough for finding the issue, then let me know.
Thanks for ur support.

**Comment by atenpas** [comment]
This seems to be related to PCL. You can have a look at https://github.com/PointCloudLibrary/pcl/issues/5237.

**Comment by Ca11m3X** [comment]
> This seems to be related to PCL. You can have a look at [PointCloudLibrary/pcl#5237](https://github.com/PointCloudLibrary/pcl/issues/5237).

Thanks for ur reply, after I upgrade to PCL 1.13.1 instead PCL 1.12.0 on Ubuntu 22.04, it works completely. Additionally, the issue is not come from `CMAKE_CXX_FLAGS` so I set it as default `set(CMAKE_CXX_FLAGS "-O3 -march=native -mtune=intel -msse4.2 -mavx2 -mfma -flto -fopenmp -fPIC -Wno-deprecated -Wenum-compare -Wno-ignored-attributes -std=c++17")`.

I really appreciate your supports.
