### ISSUE TITLE
Axis in last figure of tutorial 2 might be wrong 

### ISSUE THREAD

**Issue by ChamzasKonstantinos** [atenpas/gpd#19]
Hey,

I think that the axes in the last ![image](https://github.com/atenpas/gpd/blob/master/tutorials/hand_frame.png) of tutorial2  are  misleading. Usually rgb corresponds to x y z axes. That would mean that approach, axis, binormal correspond to the x,y,z axes respectively. However in the current implementation approach-> x , binormal->y and axis->z. For the image to be correct axis should point upwards instead of downwards and be coloured blue  and also binormal should be painted green. I am just pointing this out  because it gave me a lot of trouble to find the correct axes and had to look in the gpg code to find out. On the other hand very good job overall , I implemented this on a fetch robot and it works like a charm it can grasp almost any object on a table. Thank you !

**Comment by atenpas** [comment]
Fixed. Closing.
