### ISSUE TITLE
Use without GPU

### ISSUE THREAD

**Issue by Raffa87** [atenpas/gpd#2]
Hi!
And thank you for your wonderful work!
I followed the tutorials and I'm getting this error: Cannot use GPU in CPU-only Caffe: check mode
I tried to change this value in lenet_solver_15_channels.prototxt
(solver_mode: CPU), but error is still present
Thank you!

**Comment by atenpas** [comment]
I've added an additional parameter, `use_gpu`, which you need to set to _false_ to use the CPU mode in Caffe. See [this file](https://github.com/atenpas/gpd/blob/49d611b94d972fbc6b3f74a10774d1d35138a5b0/launch/caffe/classifier_15channels.launch#L8).
