### ISSUE TITLE
Training new model

### ISSUE THREAD

**Issue by akash-greyorange** [atenpas/gpd#23]
Hello @atenpas ,
 I recently started using GPD and software works just awesome. I went into generating training data as well as grasp images nodes but not found any node for creating new model with that dataset generated.Is it released?Would like to know more about the same.

**Comment by atenpas** [comment]
There is no node for this. You can do this through _Caffe_'s command line tools or its Python interface.

**Comment by akash-greyorange** [comment]
Ok Thanks for quick response.I am newbie to caffee as well as learning based grasp planning.Are there any guidelines for training model through caffe's command line tools?Can you share a relevant link with me so as to get started.
