### ISSUE TITLE
GraspConfigList to moveit_msgs/Grasp Message

### ISSUE THREAD

**Issue by Raffa87** [atenpas/gpd#3]
Hi!
This is not a "pure" issue: I would like to ask you how to use your work with moveit "pick" action. For example, how can I translate from GraspConfigList to moveit_msgs/Grasp?
Many thanks!

**Comment by atenpas** [comment]
**GraspConfigList** is a list of possible grasp poses. So, you should first decide which grasp you want to execute. You should use inverse kinematics to figure out which grasps can be reached by the robot. After filtering those grasps out, you can use heuristics to decide which grasp to execute (e.g., distance to the current hand pose).

*grasp_pose* in the **moveit_msgs/Grasp** message corresponds to the pose information in the **GraspConfig** message, and *grasp_quality* corresponds to _score_. You would need to fill in the remaining fields in **moveit_msgs/Grasp**. For example, *pre_grasp_posture* is in joint space and could be calculated based on the information in *grasp_pose* and the geometry of your robot hand.
