### ISSUE TITLE
confuse about some grasps

### ISSUE THREAD

**Issue by bringBackm** [atenpas/gpd#30]
l run the tutorial1.launch under ROS with Kinect, and visualize the grasps in Rviz.
Some grasps always seem to grasp the "boundary" of the PointClouds.
l am confused by this phenomenon, and do not know how to resolve this problem. 
Below is the picture l take under Ubuntu.

![issue](https://user-images.githubusercontent.com/24916161/38194333-7e08b18a-36a9-11e8-8258-15c237dd13b1.png)

**Comment by atenpas** [comment]
GPD finds grasps anywhere in the point cloud which includes the boundary. I suggest using [CloudSamples] (https://github.com/atenpas/gpd/blob/master/msg/CloudSamples.msg) or [CloudIndexed](https://github.com/atenpas/gpd/blob/master/msg/CloudIndexed.msg) which allows you to tell GPD where to search for grasps. For example, if your objects are on the floor, you can remove the floor plane and only send the indices of points that are above the floor.

**Comment by bringBackm** [comment]
@atenpas   Thank you for replying!

**Comment by WwYyFan** [comment]
@bringBackm Hi,I also encountered this problem,and I have read [CloudSamples](https://github.com/atenpas/gpd/blob/master/msg/CloudSamples.msg),but I don't know how to use it,Have you solved this problem?Can you tell me how to solve it?Thanks.

**Comment by bringBackm** [comment]
@WwYyFan  
Sorry for the late reply, really busy these time.
As mentioned by atenpas, you can do the segmentation to the pointcloud.
