### ISSUE TITLE
How is the score computed?

### ISSUE THREAD

**Issue by haudren** [atenpas/gpd#32]
Hello,

Thank you for releasing this code, it is very nice ! However I wondered how the "score" of a grasp is computed. After a quick glance at the paper, I understand that the NN is trained on a binary classification problem, which means that it will output a 0-1 probability. Then, you mention a heuristic that prioritizes vertical grasps. Is the score outputted in say `tutorial1` the output of this heuristic? I had a look at the code but it seems that you take the score directly out of the Caffe network.

Thanks again !

**Comment by atenpas** [comment]
You're right. The score is the output of the Caffe network.

**Comment by haudren** [comment]
Ok great! The score seems to be 0-1000, is there some sort of scaling going on ?

**Comment by haudren** [comment]
This is what I gathered after inspecting the code :) Thanks a lot for your time !
