### ISSUE TITLE
camera_position

### ISSUE THREAD

**Issue by yuanyangman** [atenpas/gpd#41]
In the file tutorial1.launch, <rosparam param="camera_position"> [0, 0, 0] </rosparam> ,which is the camera_position's reference frame or what [0, 0, 0] means?  ;  Also, when I change this parameters:<rosparam param="workspace_grasps"> [0.55, 1.0, -0.41, 0.03, -0.29, 1.0] </rosparam> , I can't see any difference, why?
Before generating the grasps in point clouds, I used the program in the PCL library to split the background of the object. But the effect is not very good. I want to know how you can get the good results in your video? would you like to share with me your code about the split the background of the object and the UR5 grasp code?
How many cameras do you use in your video ? and the positions of the cameras ?

**Comment by atenpas** [comment]
Yes, `camera_position` is the position at which the camera was located when the point cloud was taken.

For the 2nd parameter, `workspace_grasps` (I think this is the one you mean), you should set `filter_grasps` to `true`.

We do not use segmentation in the way that you describe. A general good technique to find grasps on objects is explained in the [2nd tutorial](https://github.com/atenpas/gpd/blob/master/tutorials/tutorial_2_grasp_select.md).

The video used two cameras (this is mentioned in the caption actually). I don't have those positions anymore, but generally, in the cluttered tabletop scenario, you want to be able to see as much as possible of the objects from each camera view.
