### ISSUE TITLE
How can I create training data

### ISSUE THREAD

**Issue by woshisj** [atenpas/gpd#49]
Can you share with me how to create a train dataset?
The Big BIRD dataset is very large and includes all angles of the object. Do you need to apply it to all the data? How did you choose? And it is the h5 file type instead of the pcd file type, which also brings a lot of trouble.

**Comment by atenpas** [comment]
You cannot do this directly with this package.

**Comment by woshisj** [comment]
> You cannot do this directly with this package. But please feel free to email me what exactly you want to do and I'll see if I can help!
Thank you for your reply. Your email is atp@ccs.neu.edu？I have sent you an email.

**Comment by atenpas** [comment]
@ruanjian0821 Please shoot me an email.

**Comment by ruanjian0821** [comment]
@atenpas 
Thanks a lot. I had sent the email. Waiting for your reply.

**Comment by prakveer** [comment]
Hi, I would also benefit from the training data. I've sent an email, thanks.

**Comment by wjydou** [comment]
@woshisj
Do you know how to create the train data?

**Comment by mlautman** [comment]
Would it be possible to keep these discussions on github rather than email? It would be nice to read through prior resolutions rather than reach out directly

**Comment by wjydou** [comment]
First of all, thank you for your late reply, I know to discuss it on github, but you are saying private mail to you. 
So  I don't understand why you say this now.



And here is what you said on GitHub.

1.Please shoot me an email.

2.You cannot do this directly with this package. But please feel free to email me what exactly you want to do and I'll see if I can help!

**Comment by atenpas** [comment]
@wjydou: I do not understand your latest comment.

In general, to create training data for arbitrary objects, you would have to write code that takes a CAD model of the object, samples random camera views, and generates a point cloud for each of those views. Those can then be processed by code similar to `data_generator`.

Please consider using https://github.com/atenpas/gpd2 which has an updated version of `data_generator`.

**Comment by wjydou** [comment]
@atenpas Thanks for your detailed answers.

**Comment by schindwall** [comment]
> @atenpas Thanks for your detailed answers.
Do you already know how to create data？

**Comment by schindwall** [comment]
> > You cannot do this directly with this package. But please feel free to email me what exactly you want to do and I'll see if I can help!
> > Thank you for your reply. Your email is [atp@ccs.neu.edu](mailto:atp@ccs.neu.edu)？I have sent you an email.

What are the author's email addresses?

**Comment by lzhnb** [comment]
> > You cannot do this directly with this package. But please feel free to email me what exactly you want to do and I'll see if I can help!
> > Thank you for your reply. Your email is [atp@ccs.neu.edu](mailto:atp@ccs.neu.edu)？I have sent you an email.

Do you solve this problem, i also want to build my own dataset, but met some trouble in both the code and the structure of source file, can you share your email and I want to discuss this with you. My email is liang13268932888@outlook.com.
Thank you for your reply.
