### ISSUE TITLE
How do I know the grasp speed?

### ISSUE THREAD

**Issue by fengyuncrawl** [atenpas/gpd#5]
hi ten Pas
After read your paper “Grasp Pose Detection in Point Clouds“,but I  don't know the speed when grasping in real world？

**Comment by atenpas** [comment]
What do you mean with "grasp speed"? The velocity of the manipulator while approaching a grasp? Or the algorithm's runtime?

**Comment by fengyuncrawl** [comment]
runtime from lift up object to place the box

**Comment by atenpas** [comment]
That depends on your robot arm and the distance between the grasped object and the box (among other factors). I would say 5-10s.

**Comment by fengyuncrawl** [comment]
Thanks to answer my question，so how do you  evaluate the recently published GQCNN https://github.com/BerkeleyAutomation/gqcnn

**Comment by atenpas** [comment]
The _issues_ section of github is intended for "tracking of tasks, enhancements, and bugs for your projects". Therefore, I'll close this threat - but feel free to drop me an email with further questions, @fengyuncrawl.
