### ISSUE TITLE
Tutorial0: Crashes on classify_grasp_candidates after generating grasp candidate

### ISSUE THREAD

**Issue by iretiayo** [atenpas/gpd#6]
Hi,
After following the installation instructions, I tried running tutorial0 (roslaunch gpd tutorial0.launch) but I get an error about classify_grasp_candidates as below. Any advice on fixing this?
I'm running ros indigo on Ubuntu 14.04
Thanks!

[ INFO] [1500147078.647140787]: Generated 8 grasp candidate sets.
Creating grasp images for classifier input ...
time for computing 8 point neighborhoods with 4 threads: 0.00681678s
[classify_grasp_candidates-2] process has died [pid 5101, exit code -11

**Comment by iretiayo** [comment]
I figured that my opencv installation was messed up. I had both opencv2 and opencv3 which were clashing. I purged libopencv* and reinstalled the ros version. Now it works.

**Comment by YuehChuan** [comment]
![gdp_error](https://user-images.githubusercontent.com/7314531/28305599-c92854be-6bce-11e7-8ed9-726215686f16.png)
Is this the same issue?

**Comment by atenpas** [comment]
No idea. It looks different though. Do you have both both opencv2 and opencv3?
