### ISSUE TITLE
Branch forward: GraspDetector::filterSideGraspsCloseToTable(...)

### ISSUE THREAD

**Issue by hauff** [atenpas/gpd#61]
There might be a bug in branch forward.

- I think you want to use `j` instead of `i` in the inner loop.
- Maybe it should be `angle < angle_thresh_` instead of `angle > angle_thresh_`.
- Isn't it easier to compute the `dist` in the following way?
  `double dist = fabs(hands[j].getGraspTop().z() - table_height_);`

```
std::vector<GraspSet> GraspDetector::filterSideGraspsCloseToTable(const std::vector<GraspSet>& hand_set_list)
{
    ...

    for (int j = 0; j < hands.size(); j++)
    {
        double angle = fabs(vert_axis_vec.transpose() * hands[i].getApproach());
        double dist = fabs((hands[i].getGraspBottom() - APPROACH_LENGTH*hands[i].getApproach())(2)) - table_height_;

        // This is a side grasps that is too close to the table.
        if (angle > angle_thresh_ && dist < table_thresh_)
        {
            is_valid(j) = false;
        }
        else
        {
            is_valid(j) = true;
            remaining++;
        }
    }

    ...
}
```

Maybe to check if one side of the gripper is under the table helps with detecting side grasps.
```
double half_width = 0.5 * outer_diameter_;
Eigen::Vector3d left_top = hands[j].getGraspTop() + half_width * hands[j].getBinormal();
Eigen::Vector3d right_top = hands[j].getGraspTop() - half_width * hands[j].getBinormal();

if (left_top.z() < table_height_ || right_top.z() < table_height_)
{
    is_valid(j) = false;
}
```

**Comment by atenpas** [comment]
Thanks for your suggestion. That filter was written for a specific case and world reference frame. I'm happy to change it if desired (but I personally don't use this filter at all anymore).

**Comment by saikishor** [comment]
@hauff @atenpas do you mean this kind of issue, could be resolved with that fix?
![screenshot from 2019-01-28 11-38-39](https://user-images.githubusercontent.com/10082428/51831301-0e5e4580-22f2-11e9-8060-bb89134af81e.png)
![screenshot from 2019-01-28 11-38-18](https://user-images.githubusercontent.com/10082428/51831304-10c09f80-22f2-11e9-86bf-a1f7005e08ab.png)

**Comment by saikishor** [comment]
@hauff I think we should make a PR with this fix. I don't know if @atenpas  has the time to take a look ober the other PR's

**Comment by saikishor** [comment]
@hauff  thanks for the confirmation :+1:

**Comment by hauff** [comment]
@saikishor, @atenpas 
as you suggested, I created a (hopefully correct) PR.

Maybe it will help. :-)

**Comment by saikishor** [comment]
In this case, aren't you using the angle parameter? Why?

**Comment by hauff** [comment]
@saikishor
I didn't use the angle because I did not want to disallow a specific approach direction. (like parallel to table surface)

But if I look at your examples, then I see that I missed something.
Maybe it is necessary to check weather the GraspBottom is also below the table.

There is a chance that I might have missed something else ?

**Comment by saikishor** [comment]
I think you have missed something. Because still I have the similar issue.
![image](https://user-images.githubusercontent.com/10082428/51839986-15de1880-230b-11e9-81ea-41368c1804b0.png)
![image](https://user-images.githubusercontent.com/10082428/51840009-2bebd900-230b-11e9-9c64-16ef47d7dafc.png)

**Comment by hauff** [comment]
In the second image it is hard to see.
Are there GraspBottom's (or fingertip's) below the table?

**Comment by saikishor** [comment]
@hauff  They are grasp bottoms. Sorry for the unclear image.

**Comment by saikishor** [comment]
I guess just replacing `i` by `j` does the trick. Below are the results.

![image](https://user-images.githubusercontent.com/10082428/51840392-43779180-230c-11e9-9986-44a874a08137.png)
![image](https://user-images.githubusercontent.com/10082428/51840398-4e322680-230c-11e9-98b0-8ea3c786493d.png)

**Comment by saikishor** [comment]
moreover, i guess the angle should be greater than angle_threshold_, else you will have all the grasp directions below it, thereby more collisions.

**Comment by hauff** [comment]
Do you filter the cloud before using the GPD package?

**Comment by saikishor** [comment]
Yes the table is not present in the cloud I give to the GPD. I only pass the table top cloud.

**Comment by hauff** [comment]
Ah now I understand.
I am pretty sure that is the reason why you get grasps starting below the table with an approach vector pointing upwards.

I did not preprocess the cloud myself, instead I used this method from GPD.
```
void GraspDetector::preprocessPointCloud(CloudCamera& cloud_cam)
{
  candidates_generator_->preprocessPointCloud(cloud_cam);
}
```
Example:
```
Eigen::Matrix3Xd view_points(3, 1);
view_points.col(0) = view_point;
CloudCamera cloud_camera(cloud_ptr, 0, view_points);

grasp_detector.preprocessPointCloud(cloud_camera);
grasps = grasp_detector.detectGrasps(cloud_camera);
```

**Comment by saikishor** [comment]
@hauff but how does it change a lot. He is also processing the point cloud and removing the layers until the table.
