### ISSUE TITLE
ImportError: No module named gpd.msg

### ISSUE THREAD

**Issue by cyu-craftnetics** [atenpas/gpd#74]
Traceback (most recent call last):
  File "select_grasp.py", line 40, in <module>
    from gpd.msg import CloudIndexed
ImportError: No module named gpd.msg

I received the import error above. How do I install the package for python to recognize? I apologize, I'm still very new to ROS packages and how they work. 

Thanks for the help!

**Comment by TheJasal** [comment]
Hi, @cyu-craftnetics 
I had build the gpd package just now, and I had meet the same problem what you said.
And the way I install the package is : 

mkdir build && cd build && cmake ..
make -j8
sudo make install 

Beforehand, you should check you ROS PYTHONPATH is correct.

Hope that helps!

**Comment by cyu-craftnetics** [comment]
It did! thanks!

**Comment by atenpas** [comment]
I'm glad this is solved. Thanks for suggesting a solution @TheJasal.
