### ISSUE TITLE
How to move gripper to reach the result of gpd

### ISSUE THREAD

**Issue by kctoayo88** [atenpas/gpd#80]
Hello,

I'm trying to implement the whole project in my environment and robot.
The result of GPD is really amazing, but when I tried to move the robot to the position of  bottom, it only can move horizontally an vertically(refer to the coordinate system axis of base_link).
In this case, If I would like to approach the object, the gripper will collide the object that I want to reach.
Therefore, I want to let robot move forward with tool direction. The gif is captured from your gpd video, and that's what I want to do.

![giphy](https://user-images.githubusercontent.com/33343560/60180247-22cb4d80-9852-11e9-847b-bd5bdf2277c8.gif)

I know this problem is not related to GPD, but I already survey it for a week and still can't got any information about it.
If you could help me this, it would be nice to me.
Thank you!

Best,
Ying

**Comment by kctoayo88** [comment]
I solved it. Sorry for disturbing.

**Comment by vipulgarg1998** [comment]
Hi @kctoayo88 
Actually, I want to implement GPD too but I am very confused about how to start with this package. Can you help me with this.
