### ISSUE TITLE
GPG VS GPD

### ISSUE THREAD

**Issue by CZ-Wu** [atenpas/gpd#82]
Hello! I have read both of your papers "Using Geometry to Detect Grasp Poses in 3D Point Clouds" and "Grasp Pose Detection in Point Clouds". I have a question that are the grasp sampling methods in these two papers the same? If not, what are the differences between them? 
Thank you very much!

**Comment by atenpas** [comment]
Those papers correspond to different repositories. "Using Geometry to Detect Grasp Poses in 3D Point Clouds" corresponds to https://github.com/atenpas/agile_grasp, and "Grasp Pose Detection in Point Clouds" corresponds to https://github.com/atenpas/gpd/.

By the way, as your question is not an issue related to the code in this repository, I'm closing this for now. Please email me about questions related to the paper(s).
